version: '3.3'
services:
  db:
    tty: true
    image: postgres
    volumes:
      - ./scripts/development/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./scripts/development/data.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  airflow_scheduler:
    tty: true
    build: .
    command: airflow scheduler
    environment:
      - AIRFLOW_HOME=~/airflow
      - AIRFLOW_CONN_OPERATIONS_EXAMPLE_DB=/code/operations.sqlite
      - AIRFLOW__CORE__DAGS_FOLDER=/code/dags
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:@db/postgres
      - GOOGLE_APPLICATION_CREDENTIALS="/code/Teste Yuca Big Query-de3f6b24ce4b.json"
    volumes:
      - .:/code
    depends_on:
      - db
  airflow_server:
    tty: true
    build: .
    command: airflow webserver --port 8080
    environment:
      - AIRFLOW_HOME=~/airflow
      - AIRFLOW_CONN_OPERATIONS_EXAMPLE_DB=/code/operations.sqlite
      - AIRFLOW__CORE__DAGS_FOLDER=/code/dags
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:@db/postgres
      - GOOGLE_APPLICATION_CREDENTIALS="/code/Teste Yuca Big Query-de3f6b24ce4b.json"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - airflow_scheduler
